
# Offense count: 1
Lint/UselessAssignment:
  Enabled: false

# Offense count: 4
Metrics/AbcSize:
  Enabled: false

# Offense count: 153
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200

# Offense count: 7
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Enabled: false

# Offense count: 7
Style/Documentation:
  Enabled: false

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 6

# Offense count: 1
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false