jruby: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-complete-1.7.16.jar"
jetty: "file://<%= File.expand_path('spec/local_mirror') %>/jetty-hightide-8.1.16.v20140903.zip"
jruby-rack: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-rack-1.1.16.jar"
http_port: 20080
https_port: 20443
ruby_version: 1.9
app_type: rack
keystore: "etc/fake.p12"
keystore_password: "foobar"
